// Public copy is shared with the native app by build-public-pages.mjs.
export const updated = '2026-10-08';
export const privacy = [
  ['In/Out and this policy', 'In/Out is developed and operated by IMR Tech SpA. It is a wellness product, not a medical device, and is not intended to diagnose or treat medical conditions. This policy covers the mobile app and inout.imrtech.xyz.'],
  ['Practice data on your phone', 'Sessions, Challenge attempts and personal bests, State Shift ratings, reported effects, program progress, badges, routines, reminders, preferences and optional profile details are stored locally. An optional profile photo is copied into the app’s private files. These are self-reported wellness records, not biometric measurements. They are not uploaded to our servers or sent to advertising or analytics providers. Guest practice works without an account.'],
  ['Accounts and launch scope', 'Account support is planned for production. The current mobile build does not yet offer account creation or cloud history sync. Where an In/Out account has been provisioned, Supabase Auth processes its email, authentication credentials, user identifier and security/session information. The website can verify an existing account for privacy requests; it does not create an account merely because someone requests deletion. Account availability does not mean local history is backed up.'],
  ['Subscriptions', 'Configured native purchases use Apple or Google billing and RevenueCat to check purchases, restore access and manage subscription entitlements. These services receive purchase and subscription records, an app-generated customer identifier, and device/app/network information necessary to operate billing. In/Out does not receive payment-card details. Purchase and entitlement information is required when you use these features. Subscriptions are optional.'],
  ['Advertising and consent', 'The Free version includes the Google Mobile Ads SDK and Google’s consent system. Live advertising requires production configuration and regional consent handling. Google may process IP-derived approximate location, device and advertising identifiers, ad interactions and diagnostics for delivery, measurement and fraud prevention, including with non-personalized ads. Practice ratings and history are not provided to Google. Pro suppresses ad requests. Review available choices in Settings → Plan & privacy → Ad privacy options. The current development setup uses test ads; final live-ad configuration requires validation before launch.'],
  ['Optional sharing', 'Sharing an exercise uploads only its cadence and any nostril instructions to Supabase. A random public link grants access for 30 days unless revoked earlier. Names, ratings and notes are excluded. Keep its revocation control on your phone. Result and milestone sharing sends only the content shown in the sharing preview to your selected destination; the recipient or service can keep a copy. No public user profile or account-ID lookup exposes your history.'],
  ['Optional welcome email', 'When enabled and explicitly requested, the welcome service sends your email, first name, selected goal, language and installation identifier to Supabase and Resend for one welcome message. It is not a marketing subscription. Retry payloads are removed on success or after the 23-hour retry window is reviewed; a salted email hash and delivery status remain for deduplication. Daily hashed installation/network counters limit abuse. The service is subject to owner configuration; disabling local retries cannot recall a sent message. Contact support to request deletion of server-side email records.'],
  ['Support and privacy requests', 'Email support receives the address and message you send. Verified online privacy requests store your account identifier, email, requested scope, status and timestamps privately in Supabase so IMR Tech SpA can process the request. Only an authenticated, email-verified account can submit through that flow. Guest users and people unable to sign in can request assistance by email. We verify ownership before disclosing or deleting protected data. Do not send passwords, payment-card details or unnecessary wellness history.'],
  ['Infrastructure, analytics and review access', 'Vercel hosts this website; Supabase hosts sharing, privacy-request and internal app-review services. They process ordinary IP/network and security information. This website adds no advertising, marketing pixels, analytics or tracking cookies. Verification tokens are used only for the active request and are not saved in browser storage. The app has no remote product-analytics or crash-reporting SDK; its event-name logger runs only in development. Apple and Google may independently handle store/device diagnostics. Internal reviewer access uses hashed installation/grant identifiers, expiry and revocation status; review credentials are never published here.'],
  ['Retention and deletion', 'Local records remain until you remove them. Settings → Local data → Delete local history removes session history and Challenge test results while retaining routines, preferences, program progress and badges. Delete all local data removes the local profile, history, preferences and saved content and cancels app reminders. Revoke exercise links in Settings → Shared links before resetting. The website cannot erase a phone’s local storage. Cloud privacy requests are requests for processing, not a claim of immediate deletion. We retain request/support records only as needed to verify and fulfill requests, prevent abuse, resolve disputes or satisfy applicable obligations. We explain any applicable exception when responding; there is no universal fixed retention period established yet. Store transaction records are controlled independently by Apple/Google, and processor logs/backups may persist under their retention rules. Deletion does not cancel a subscription or erase copies shared with others.'],
  ['Security and international processing', 'We use HTTPS for configured network services, restricted server access and ownership verification for privacy requests. Local data is protected by the app sandbox but has no separate database encryption. No system offers absolute security. Device backups and transfers are controlled by your operating system and can retain copies. Providers may process information outside your country; privacy questions and requests can be directed to IMR Tech SpA through Support.'],
  ['Children, choices and changes', 'In/Out is not directed at children. Do not provide a child’s personal information through support or account forms. Contact us if you believe such information was provided. Optional photos and reminders use the system picker/notification permission; the app does not request camera, microphone, contacts, location or health-sensor access. We update this policy as practices change and show the effective and last-updated dates here. Account and advertising launch changes require a corresponding policy and store-disclosure review.'],
];
export const terms = [
  ['Using In/Out', 'In/Out is developed and operated by IMR Tech SpA. By using the service, you agree to these terms. Use it only where you are legally able to agree, and obtain parent or guardian involvement where required. Mandatory consumer rights continue to apply.'],
  ['Wellness and safety', 'In/Out provides breathing exercises, Challenges and personal progress tools for general wellness. It does not diagnose or treat medical conditions and does not guarantee an outcome. Breathing exercises and breath holds can cause discomfort or dizziness. Stop and breathe naturally if you feel unwell. Practice seated or lying in a safe place, never while driving, operating machinery, swimming, bathing or near water. Holds are optional and must not be used competitively. Consult a qualified professional if unsure whether a practice is suitable. In/Out is not an emergency service.'],
  ['Accounts and your content', 'Guest practice is available. Production account support is planned; the current mobile build has no sign-in or cloud history sync. Where accounts are available, protect your credentials and provide accurate information. Keep any copies you need before deleting local data. You control optional sharing; recipients may retain shared copies. Do not upload another person’s private information without authorization.'],
  ['Free and Pro', 'Core breathing features are available without a subscription. Pro unlocks the features shown in the app. Free use may include advertising according to the Privacy Policy and your available consent choices. Feature availability can vary by version and platform.'],
  ['Purchases, renewal and cancellation', 'The app sells configured weekly, monthly or yearly Pro subscriptions through Apple App Store or Google Play, using RevenueCat to manage entitlements. Before confirming, review the store’s actual localized price, billing period and any eligible trial or introductory offer. Recurring subscriptions renew unless cancelled through your store account under the store’s terms. No trial or price is promised here. Cancellation normally stops the next renewal; current access is subject to the paid period and store status. Deleting data, requesting account deletion or uninstalling does not cancel billing.'],
  ['Restore and refunds', 'Use Settings → Plan & privacy → Pro & subscriptions → Restore purchases with the store account used for purchase. Manage subscriptions and refund requests through the relevant store. Store rules and applicable consumer law govern refunds. The website does not sell subscriptions or process card payments.'],
  ['Acceptable use and intellectual property', 'Do not abuse the service, attempt unauthorized access, bypass access controls, disrupt infrastructure or use shared links to distribute unlawful material. IMR Tech SpA and its licensors retain rights to the app, branding and original content. Your personal use does not transfer those rights. You retain your rights in content you supply and permit processing needed for features you choose.'],
  ['Availability, changes and termination', 'We may update features, fix defects, or restrict abusive use. Availability is not guaranteed; local records can be lost when a device or app storage is lost. Material changes will be reflected in the relevant terms or product notices. You may stop using the service and request account/data deletion through the linked pages.'],
  ['Responsibility and liability', 'You are responsible for choosing a safe place and comfortable practice and for safeguarding your device. To the extent permitted by applicable law, the service is provided as available without guarantees of uninterrupted availability or a particular wellness result. Liability is limited only where the law allows; these terms do not exclude rights or liabilities that cannot lawfully be excluded.'],
  ['Operator and questions', 'The operator is IMR Tech SpA. Contact us through Support for product, billing or terms questions. Applicable mandatory consumer protections remain in effect.'],
];
export const support = [
  ['Subscriptions and restore', 'Open Settings → Plan & privacy → Pro & subscriptions, then Restore purchases. Use the same Apple or Google account used to buy Pro. Cancel renewal or request a refund through that store. Deleting local data does not cancel a subscription.'],
  ['Accounts and data', 'Guest practice is available now; production account support is planned. The current mobile build stores history on your device and does not sync it to an account. Use the deletion pages for local controls, verified account requests and help when you cannot sign in.'],
  ['A session paused or sound is missing', 'App switching, screen lock and supported interruptions pause the guide. Return and choose Resume, Restart or End session. Check Sound in Settings, device volume and headphones. Audio follows the iPhone silent switch. Haptic behavior depends on your device.'],
  ['Offline use and moving phones', 'Breathing, saved routines, State Shift and history work offline. Billing, hosted shares, email and privacy requests need a connection. Local history is not cloud-backed by In/Out; device backups and transfers depend on your platform.'],
  ['Safety', 'Stop if you feel dizzy or unwell. Breathe naturally in a safe seated or lying position. Never practice while driving or in or near water. In/Out is a wellness tool, not emergency or medical care.'],
  ['Contact IMR Tech SpA', 'For technical help, include your app version, phone model, operating system and a brief description. Do not include passwords or unnecessary private wellness information. Privacy and subscription questions are welcome at the contact below.'],
];
