export const voices = {
  en: [
    require("../assets/audio/en/inhale.mp3"),
    require("../assets/audio/en/top-up.mp3"),
    require("../assets/audio/en/exhale.mp3"),
    require("../assets/audio/en/complete.mp3"),
    require("../assets/audio/en/hold.mp3"),
    require("../assets/audio/en/hum.mp3"),
    require("../assets/audio/en/rest.mp3"),
    require("../assets/audio/en/recover.mp3"),
    require("../assets/audio/en/natural.mp3"),
    require("../assets/audio/en/inhale-left.mp3"),
    require("../assets/audio/en/inhale-right.mp3"),
    require("../assets/audio/en/exhale-left.mp3"),
    require("../assets/audio/en/exhale-right.mp3"),
  ],
  es: [
    require("../assets/audio/es/inhale.mp3"),
    require("../assets/audio/es/top-up.mp3"),
    require("../assets/audio/es/exhale.mp3"),
    require("../assets/audio/es/complete.mp3"),
    require("../assets/audio/es/hold.mp3"),
    require("../assets/audio/es/hum.mp3"),
    require("../assets/audio/es/rest.mp3"),
    require("../assets/audio/es/recover.mp3"),
    require("../assets/audio/es/natural.mp3"),
    require("../assets/audio/es/inhale-left.mp3"),
    require("../assets/audio/es/inhale-right.mp3"),
    require("../assets/audio/es/exhale-left.mp3"),
    require("../assets/audio/es/exhale-right.mp3"),
  ],
  pt: [
    require("../assets/audio/pt/inhale.mp3"),
    require("../assets/audio/pt/top-up.mp3"),
    require("../assets/audio/pt/exhale.mp3"),
    require("../assets/audio/pt/complete.mp3"),
    require("../assets/audio/pt/hold.mp3"),
    require("../assets/audio/pt/hum.mp3"),
    require("../assets/audio/pt/rest.mp3"),
    require("../assets/audio/pt/recover.mp3"),
    require("../assets/audio/pt/natural.mp3"),
    require("../assets/audio/pt/inhale-left.mp3"),
    require("../assets/audio/pt/inhale-right.mp3"),
    require("../assets/audio/pt/exhale-left.mp3"),
    require("../assets/audio/pt/exhale-right.mp3"),
  ],
};
