import { revenueCatAdapter } from "../src/subscription-providers/revenuecat";
import { SubscriptionError } from "../src/subscriptions";
const mockSdk = { configure: jest.fn(), getCustomerInfo: jest.fn(), getOfferings: jest.fn(), purchasePackage: jest.fn(), restorePurchases: jest.fn(), addCustomerInfoUpdateListener: jest.fn(), removeCustomerInfoUpdateListener: jest.fn() };
jest.mock("react-native-purchases", () => ({ default: mockSdk }));
test("production adapter preserves anonymous identity, standard packages, intro metadata, restore and lifecycle updates", async () => {
  const info = { requestDate: new Date(1000).toISOString(), entitlements: { all: { pro: { productIdentifier: "fixture", expirationDate: new Date(10000).toISOString(), isActive: true, willRenew: true, periodType: "NORMAL" } } }, managementURL: "https://example.test/manage" };
  const monthly = { product: { priceString: "$fixture", introPrice: { priceString: "$0", cycles: 1, period: "P7D" } } };
  const annual = { product: { priceString: "$annual" } };
  mockSdk.getCustomerInfo.mockResolvedValue(info);
  mockSdk.restorePurchases.mockResolvedValue(info);
  mockSdk.purchasePackage.mockResolvedValue({ customerInfo: info });
  mockSdk.getOfferings.mockResolvedValue({ current: { monthly, annual } });
  const provider = revenueCatAdapter("appl_fixture");
  expect(mockSdk.configure).toHaveBeenCalledWith({ apiKey: "appl_fixture" });
  const offers = await provider.offers(); expect(offers.map(o => o.id)).toEqual(["monthly", "annual"]);
  expect(offers[0].introductoryOffer).toEqual({ price: "$0", periods: 1, period: "P7D" });
  expect((await provider.purchase("monthly")).active).toBe(true);
  expect(mockSdk.purchasePackage).toHaveBeenCalledWith(monthly);
  expect((await provider.restore()).source).toBe("store");
  expect(await provider.managementUrl()).toBe("https://example.test/manage");
  mockSdk.purchasePackage.mockRejectedValueOnce({ code: "20" });
  await expect(provider.purchase("annual")).rejects.toMatchObject({ reason: "pending" });
  mockSdk.purchasePackage.mockRejectedValueOnce({ userCancelled: true });
  await expect(provider.purchase("annual")).rejects.toMatchObject({ reason: "cancelled" });
  mockSdk.purchasePackage.mockRejectedValueOnce({ message: "SDK-specific private failure" });
  await expect(provider.purchase("annual")).rejects.toBeInstanceOf(SubscriptionError);
  const listener = jest.fn(); const cleanup = provider.listen!(listener);
  const update = mockSdk.addCustomerInfoUpdateListener.mock.calls[0][0];
  update({ ...info, entitlements: { all: {} } }); expect(listener).toHaveBeenCalledWith(expect.objectContaining({ active: false, status: "free" }));
  cleanup(); expect(mockSdk.removeCustomerInfoUpdateListener).toHaveBeenCalledWith(update);
});
